CREATE TABLE audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL REFERENCES organizations (id),
    ticket_id       BIGINT      NOT NULL,
    event_type      VARCHAR(50) NOT NULL,
    actor_user_id   BIGINT,
    summary         TEXT        NOT NULL,
    occurred_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_ticket_id ON audit_logs (ticket_id);
