CREATE TABLE audit_logs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL REFERENCES organizations (id),
    -- Not a foreign key, for the same reason as notifications.ticket_id -
    -- the audit trail must survive the ticket it describes being deleted.
    ticket_id       BIGINT      NOT NULL,
    event_type      VARCHAR(50) NOT NULL,
    actor_user_id   BIGINT,
    summary         TEXT        NOT NULL,
    -- When the underlying domain event happened, not when this consumer
    -- processed it (created_at) - the two can differ under consumer lag.
    occurred_at     TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_ticket_id ON audit_logs (ticket_id);
