-- organization_id is nullable: SUPER_ADMIN accounts are platform-level
-- (they manage organizations themselves) and are not scoped to a tenant.
-- Every other role always has an organization_id.
CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES organizations (id),
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Every organization-scoped query (e.g. "list users in org X") filters on
-- this column, so it needs its own index rather than relying on the
-- implicit index the FK constraint alone does not provide in Postgres.
CREATE INDEX idx_users_organization_id ON users (organization_id);
