CREATE TABLE teams
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id),
    name            VARCHAR(255) NOT NULL,
    description     VARCHAR(1000),
    team_lead_id    BIGINT REFERENCES users (id),
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_teams_organization_id ON teams (organization_id);
