CREATE TABLE tickets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id),
    project_id      BIGINT       NOT NULL REFERENCES projects (id),
    team_id         BIGINT REFERENCES teams (id),
    created_by      BIGINT       NOT NULL REFERENCES users (id),
    assigned_to     BIGINT REFERENCES users (id),
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    priority        VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    due_date        TIMESTAMPTZ,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Single-column indexes for the individual filters GET /api/tickets
-- supports (Section 15/16 of the spec: status, priority, assignee, team,
-- project - project_id and team_id already get an index from their FK,
-- Postgres does not create one automatically, so it's explicit here too).
CREATE INDEX idx_tickets_organization_id ON tickets (organization_id);
CREATE INDEX idx_tickets_project_id ON tickets (project_id);
CREATE INDEX idx_tickets_team_id ON tickets (team_id);
CREATE INDEX idx_tickets_assigned_to ON tickets (assigned_to);
CREATE INDEX idx_tickets_status ON tickets (status);
CREATE INDEX idx_tickets_priority ON tickets (priority);
CREATE INDEX idx_tickets_created_at ON tickets (created_at);

-- Composite indexes matching the two most common real query shapes:
-- every ticket list is scoped to one organization first, then usually
-- filtered by status or sorted by recency within that organization.
-- A single-column organization_id index alone would still require
-- scanning/filtering all of that org's tickets for the second predicate.
CREATE INDEX idx_tickets_org_status ON tickets (organization_id, status);
CREATE INDEX idx_tickets_org_created_at ON tickets (organization_id, created_at DESC);
