CREATE TABLE tickets
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL REFERENCES organizations (id),
    project_id      BIGINT       NOT NULL REFERENCES projects (id),
    team_id         BIGINT REFERENCES teams (id),
    created_by      BIGINT       NOT NULL REFERENCES users (id),
    assigned_to     BIGINT REFERENCES users (id),
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    priority        VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    due_date        TIMESTAMPTZ,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_tickets_organization_id ON tickets (organization_id);
CREATE INDEX idx_tickets_project_id ON tickets (project_id);
CREATE INDEX idx_tickets_team_id ON tickets (team_id);
CREATE INDEX idx_tickets_assigned_to ON tickets (assigned_to);
CREATE INDEX idx_tickets_status ON tickets (status);
CREATE INDEX idx_tickets_priority ON tickets (priority);
CREATE INDEX idx_tickets_created_at ON tickets (created_at);

CREATE INDEX idx_tickets_org_status ON tickets (organization_id, status);
CREATE INDEX idx_tickets_org_created_at ON tickets (organization_id, created_at DESC);
