-- token_hash stores SHA-256(raw token), never the raw token itself - see
-- RefreshToken's Javadoc for why a deterministic hash (not BCrypt) is the
-- right choice here.
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ  NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    -- Optimistic lock: two concurrent /refresh calls presenting the same
    -- token could otherwise both read revoked=false before either commits
    -- its rotation, minting two valid sessions from one token. See
    -- RefreshToken's Javadoc.
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Every refresh and logout call looks up by user for cleanup/auditing
-- purposes, in addition to the unique lookup by token_hash.
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
