CREATE TABLE notifications
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL REFERENCES organizations (id),
    recipient_user_id BIGINT      NOT NULL REFERENCES users (id),
    ticket_id         BIGINT      NOT NULL,
    type              VARCHAR(30) NOT NULL,
    message           TEXT        NOT NULL,
    read              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient_user_id, read);
