CREATE TABLE notifications
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL REFERENCES organizations (id),
    recipient_user_id BIGINT      NOT NULL REFERENCES users (id),
    -- Not a foreign key: a ticket can be deleted (ORG_ADMIN-only DELETE
    -- /api/tickets/{id}), and a notification about it should still be
    -- readable in the recipient's history afterward rather than being
    -- cascade-deleted or blocking the ticket's deletion.
    ticket_id         BIGINT      NOT NULL,
    type              VARCHAR(30) NOT NULL,
    message           TEXT        NOT NULL,
    read              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Every read is "this user's notifications, unread first/only".
CREATE INDEX idx_notifications_recipient ON notifications (recipient_user_id, read);
